#ifndef EMBEDDED_COMPILERS_EXERCISE_H
#define EMBEDDED_COMPILERS_EXERCISE_H

#ifndef EMBEDDED_COMPILERS_N
#error "EMBEDDED_COMPILERS_N must be defined"
#endif

#ifndef EMBEDDED_COMPILERS_K
#error "EMBEDDED_COMPILERS_K must be defined"
#endif

#ifndef EMBEDDED_COMPILERS_BLOCK_SIZE
#error "EMBEDDED_COMPILERS_BLOCK_SIZE must be defined"
#endif

#endif //EMBEDDED_COMPILERS_EXERCISE_H
